# -*- coding: utf-8 -*-

import pytest

import cal


def test_cal():
    """

        test cases:	
        - n = 19
        - 0 < dds <= 6 e 28 <= n <= 31
        (invalid cases are discarded by the main, as both parameters
         are generated by the first_of_month and number_of_days methods, which are already being tested)
    """
    expected_result_1 = "       1  2 14 15 16\n17 18 19 20 21 22 23\n24 25 26 27 28 29 30"
    expected_result_2 = "          1  2  3  4\n 5  6  7  8  9 10 11\n12 13 14 15 16 17 18\n19 20 21 22 23 24 25\n26 27 28 29 30 "

    assert cal.cal(2, 19) == expected_result_1
    assert cal.cal(3, 30) == expected_result_2


@pytest.mark.parametrize('input, expected_result', [
    (4, True),     #Year less than 1752 and multiple of 4
    (1501, False), #Year less than 1752 and non-multiple of 4
    (1900, False), #Year greater than 1752 and multiple of 100
    (1903, False), #Year greater than 1752 and not a multiple of 4    
    (1904, True),  #Year greater than 1752 and multiple of 4
    (2000, True),  #Year greater than 1752 and multiple of 400
])
def test_is_leap(input, expected_result):
    
    actual = cal.is_leap(input) 
    assert  actual == expected_result


@pytest.mark.skipif(True, reason = 'simply ignoring for now')
def test_mutation_is_leap():

    assert cal.is_leap(1752) == True



@pytest.mark.parametrize('input, expected_result', [
    ((1, 1), 6),      #Non-leap year
    ((1, 4), 2),      #Leap year, month <= 2
    ((5, 4), 4),      #Leap year, month> 2
    ((9, 1752), 2),   #Year 1752, month <= 9    
    ((11, 1752), 3),  #Year 1752, month> 9
])
def test_first_of_month(input, expected_result):
    
    month, year = input
    actual = cal.first_of_month(month, year) 
    assert  actual == expected_result



@pytest.mark.parametrize('input, expected_result', [
    (1801, 4), #Year greater than 1800 (expected: Thursday, 4)
    (1780, 6), #Year less than 1800 and greater than 1752 (expected: Saturday, 6)
    (1500, 3), #Year less than 1752 (expected: Wednesday, 3)
])
def test_jan1(input, expected_result):
    
    actual = cal.jan1(input) 
    assert  actual == expected_result



@pytest.mark.parametrize('input, expected_result', [
    ((3, 2001), 31),   #Non-leap year
    ((2, 2000), 29),   #Leap year, month <= 2
    ((3, 2000), 31),   #Leap year, month> 2
    ((9, 1752), 19),   #Year 1752, month <= 9   
    ((12, 1752), 31),  #Year 1752, month> 9
])
def test_number_of_days(input, expected_result):
    
    month, year = input
    actual = cal.number_of_days(month, year) 
    assert  actual == expected_result
